### ISSUE TITLE
[FIX] 팝업 이미지 여러 개 받을 수 있도록 변경 

### ISSUE THREAD

**Issue by eundeang** [CHEFLEA/Cheflea-Server#49]
## Description
팝업 이미지 여러 개 받을 수 있도록 변경

## To-Do
- [x] 팝업 단건 조회
- [ ] 팝업 전체 조회
- [ ] 팝업 예약 전 팝업 정보 조회
